# Configuration file for Synapse.
#
# This is a YAML file: see [1] for a quick introduction. Note in particular
# that *indentation is important*: all the elements of a list or dictionary
# should have the same indentation.
#
# [1] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
#
# For more information on how to configure Synapse, including a complete accounting of
# each option, go to docs/usage/configuration/config_documentation.md or
# https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html
server_name: "matrix.dev-stack.local"
pid_file: /data/homeserver.pid
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
database:
  name: psycopg2
  args:
    user: dev-stack-admin
    password: 123DevStack!
    database: synapse-matrix-db
    host: postgres # The service name defined in your docker-compose file
    cp_min: 5
    cp_max: 10
log_config: "/data/matrix.dev-stack.local.log.config"
media_store_path: /data/media_store
registration_shared_secret: "7:c1tSY0OTzZ.Nay6H+ncxV6~ha8aD:zOSp8hZA@4ehkVhbKMj"
report_stats: false
macaroon_secret_key: "ovCnBuM&-*d0~U-T3nqQxr+wm^8iZuNj^u1iwxqj;hZ=;KkQGo"
form_secret: "K2^=ErkWpF#9t&=@H*fPece2KZUx#2GzPaI.ESf#N@Vy.Yq&=k"
signing_key_path: "/data/matrix.dev-stack.local.signing.key"
trusted_key_servers:
  - server_name: "matrix.org"


# vim:ft=yaml